# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269550a3948d49d83a98ecaf099ae00a8bb720ab684ab3dae603de4ad47558c4768da4bd5767f760409244b3a9dd9185a5ba12316be7d5b2d0068680648f7d23

test:
  secret_key_base: 7e319799bd386c4ba40a86416c83fbd6e2c4e8cf14309980b3b3a09f10716a308ad7c3550e2f2768e7747b836fd7f81dfb1a6f664e8e7e85e5f5e70861929d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
